### ISSUE TITLE
🐛 [BUG] - Notications setting

### ISSUE THREAD

**Issue by GeekyKartikey** [push-protocol/push-dapp#1491]
### Expected Behaviour

During updation of notificaion settings, lower limit of vairables like Time Interval, price change, etc. can 0/1.

### Current Behaviour

Currenly while decreasing the current seting of time interval/price change percentage from 3 to either 2 or 1 or lower the lowest limit is again coming as 3

For refrence visit - https://www.notion.so/pushprotocol/Issue-with-notification-Setting-12ec92ef1ed6449da6558afb700d32e7

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Dapp Env

Prod (app.push.org)

**Comment by rohitmalhotra1420** [comment]
@abhishek-01k assigning this to you. Please connect with @mishramonalisha76 in case you have any queries.
