### ISSUE TITLE
🐛 [BUG] - Change the notifications.subscribe to subscribeV2 to add settings for the users

### ISSUE THREAD

**Issue by abhishek-01k** [push-protocol/push-dapp#1514]
### Expected Behaviour

Opt-In should call subscribe V2 instead of subscribe V1 API because user settings are not getting updated for the channels that the user is opting into. Changing it to subscribe V2 will fix this issue

### Current Behaviour

Currently its on subscribe v1

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Dapp Env

Prod (app.push.org), Staging (staging.push.org), Dev (dev.push.org)

**Comment by rohitmalhotra1420** [comment]
@abhishek-01k could you take a pull of [this](https://github.com/push-protocol/push-dapp/pull/1493) PR in your branch and move forward with it.

**Comment by rohitmalhotra1420** [comment]
QA is completed by Kartikey. Closing the ticket.
https://github.com/push-protocol/push-dapp/pull/1524#issuecomment-2135126934
