### ISSUE TITLE
[BUG]: No Channel logo in notification 

### ISSUE THREAD

**Issue by aeyshubh** [push-protocol/push-dapp#1525]
### I confirm that I searched through the issues and didn't find my problem.

- [X] Confirm

### Bug description

The channel logo is not visible in notifications.
- I tested it on two different browsers (Brave and chrome)
- Channels i referred : Shapeshif, Eth tracker, Btc tracker
 

### Screenshots
![Shapeshift Notification](https://github.com/push-protocol/push-website/assets/50445649/a8107073-b031-4b8b-9fbb-520b2a011974)

### Expected Behaviour

Channel Logo should be visible in the notifications.

### Browsers

Chrome

**Comment by rohitmalhotra1420** [comment]
After analysing the codebase we concluded that this is working on frontend. Im closing the ticket for now.
