### ISSUE TITLE
👾 [Other] - <Research on the dashboard apis and ui components>

### ISSUE THREAD

**Issue by mishramonalisha76** [push-protocol/push-dapp#1526]
### Description

https://www.notion.so/pushprotocol/Dashboard-Development-bfffc6380fbe4e78b865a0ac219f5363

### Dapp Env

Prod (app.push.org), Staging (staging.push.org), Dev (dev.push.org)

**Comment by rohitmalhotra1420** [comment]
@mishramonalisha76 @abhishek-01k here what you guys need to do:

- List down all the feature section of the new dashboard page you guys will be working on. 
https://www.figma.com/design/FvJL0JWHlsVohsHTERB1Lh/Push-Design-Foundations-[Future]?node-id=973-3716&m=dev

- List all the API which needs changes to implement the new functionalities on Dashboard page. This needs to be documented here:https://www.notion.so/pushprotocol/Going-through-the-existing-Backend-APIs-277c850acd574e7189f16e44d7501b64

-  List all the API which needs to be implemented from scratch to implement the new functionalities on Dashboard page: To be documented here: https://www.notion.so/pushprotocol/Look-if-we-need-new-endpoints-developed-from-scratch-ab86103fc55944b284a43903ba2ed753
