### ISSUE TITLE
🐛 [BUG] - <MOBILE: Mobile login only shows when chat once you go out and come back in>

### ISSUE THREAD

**Issue by corlard3y** [push-protocol/push-dapp#1558]
### Expected Behaviour

Will be back to this

### Current Behaviour

Mobile login only shows when chat once you go out and come back in

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Dapp Env

Prod (app.push.org), Staging (staging.push.org), Dev (dev.push.org)

**Comment by rohitmalhotra1420** [comment]
Already fixed.
