### ISSUE TITLE
🐛 [BUG] - [BUMP SDK IN DAPP] - Fix the the modal close behaviour on click outside modal 

### ISSUE THREAD

**Issue by HarshRajat** [push-protocol/push-dapp#1561]
When we start creating the group, the modal goes away on any render changes or even when night mode is toggled. Having a state that persists instead of modal wrapper that is non-persistent should solve the issue.

**Comment by abhishek-01k** [comment]
This is an sdk issue so have created a ticket on the sdk side -> https://github.com/push-protocol/push-sdk/issues/1338

So, we can close this issue @rohitmalhotra1420
