### ISSUE TITLE
🐛 [BUG] - Chat view to List view error - Mobile dApp

### ISSUE THREAD

**Issue by 0x12zee** [push-protocol/push-dapp#1564]
### Expected Behaviour

user should be able to go out of chat view to list view and be able to go back into the same chat.

### Current Behaviour

On mobile dapp if I go back from a chat to list view, I cannot enter the chat again. Until I click on another chat.

### Reproduction steps

```bash
1. Go to 'app.push.org/chat'
2. Click on a chat and go in view where you can see messages.
3. On Mobile breakpoint go back to list view where you can view chats from multiple people.
4. Go back into the chat you came out of again. You won't be able to.
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Dapp Env

Prod (app.push.org)

### Browsers

Firefox, Chrome, Safari, Microsoft Edge

**Comment by rohitmalhotra1420** [comment]
Tested by @abhishek-01k and @rohitmalhotra1420 . Moving this to Done.
