### ISSUE TITLE
Create Frontend Development and deployment guidelines for SDK and Dapp

### ISSUE THREAD

**Issue by rohitmalhotra1420** [push-protocol/push-dapp#1568]
To fix the current confusion around development and deployment for DApp and SDK, this ticket focuses on creating a notion document for guidelines related to this process.

**Comment by rohitmalhotra1420** [comment]
@corlard3y to review this and close the ticket: https://www.notion.so/pushprotocol/Development-and-Deployment-process-for-DApp-and-Push-SDK-f84ad6efc92544b8bf9ef60d9ee7a108

**Comment by corlard3y** [comment]
Gone through the document, and it LGTM
