### ISSUE TITLE
🐛 [BUG] - Delegate of a channel is not visible on Alias Chain

### ISSUE THREAD

**Issue by abhishek-01k** [push-protocol/push-dapp#1573]
### Expected Behaviour

Delegates should be visible on the Alias chains.

### Current Behaviour

Delegates are not visible on the Alias chains.

### Reproduction steps

```bash
1. Go to staging.push.org/dashboard
2. Change the chain to Alias Chain
3. No delegate are displayed
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Dapp Env

Staging (staging.push.org), Dev (dev.push.org)

**Comment by rohitmalhotra1420** [comment]
We will deploy this one staging and Aman needs to test out these changes there.

@abhishek-01k to remind @rohitmalhotra1420  to deploy this on staging on Monday 27th May

**Comment by rohitmalhotra1420** [comment]
@abhishek-01k please take a confirmation from Aman on this ticket that the fix we deployed on dev and staging is working so we can move ahead with prod deployment.

**Comment by abhishek-01k** [comment]
@rohitmalhotra1420 Aman commented on the PR. We can close this issue
