### ISSUE TITLE
🐛 [BUG] -Some Notifications are missing from the Inbox 

### ISSUE THREAD

**Issue by abhishek-01k** [push-protocol/push-dapp#1592]
### Expected Behaviour

All Notifications should be visible.

### Current Behaviour

Some notifications are missing in the Inbox Page

### Reproduction steps

```bash
1. Go to dapp -> inbox
2. Scroll down to bottom 
4. You will see some notifications missing
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Dapp Env

Prod (app.push.org), Staging (staging.push.org), Dev (dev.push.org)

**Comment by rohitmalhotra1420** [comment]
@abhishek-01k let's get this tested from Kartikey and then close the ticket.
