### ISSUE TITLE
😈 [Feature] - <Base Chain Support>

### ISSUE THREAD

**Issue by corlard3y** [push-protocol/push-dapp#1607]
### Feature name

Base Chain Support

### Describe the Enhancement

CoinBase has invited us to deploy on Base chain, with the biggest incentive being the integration of Push Notifications in Coinbase Wallet.
So we are basically just adding Base chain support, it’s just going to be a new chain like the others we have, from polygon, Arbitrum, cyber and the rest that have been added beforehand. So this is a new one called Base Chain - IIntegration of Push will enable native visibility of notifications from base ecosystem in coinbase wallet. So you can create channels, send notifications on this chain.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Dapp Env

Prod (app.push.org), Staging (staging.push.org), Dev (dev.push.org)

**Comment by rohitmalhotra1420** [comment]
@corlard3y to get it functionally reviewed from Abhishek and Monalisha, get Qa done by Kartikey and update the ticket description.
