### ISSUE TITLE
🐛 [BUG] - [BUMP SDK IN DAPP] - Fix ui representation for domain resolution

### ISSUE THREAD

**Issue by mishramonalisha76** [push-protocol/push-dapp#1612]
### SDK version 
[1.0.0-exp.12](https://www.npmjs.com/package/@pushprotocol/uiweb/v/1.0.0-exp.12)
### Expected Behaviour

Searching a domain should show only domain

### Current Behaviour

Searching  a domain shows address first and then shows the domain name

### Reproduction steps

```bash
1. Go to '/chat'
2. Connect and unlock profile
3. Search a domain address (example - fabio.eth)
4. Should see the expected behaviour
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Dapp Env

Prod (app.push.org), Staging (staging.push.org), Dev (dev.push.org)

**Comment by rohitmalhotra1420** [comment]
To be closed once https://github.com/push-protocol/push-dapp/issues/1561 is merged.
