### ISSUE TITLE
😈 [Feature Enhancement] - Integrate the API in the Rewards Page and update the rewards Page 

### ISSUE THREAD

**Issue by abhishek-01k** [push-protocol/push-dapp#1655]
### Describe the Enhancement

Implement the following feature on the rewards Page

- Dark mode support
- API integration
- mobile version
- Null States/error handling

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Dapp Env

Prod (app.push.org), Staging (staging.push.org), Dev (dev.push.org)

**Comment by rohitmalhotra1420** [comment]
Closing this as the base functionality for this ticket is developed
