### ISSUE TITLE
🐛 [BUG] - <Channel creation not working, got stuck on Enable Push Profile: Dev environment>

### ISSUE THREAD

**Issue by pranshurastogi** [push-protocol/push-dapp#1670]
### Expected Behaviour

* Ideally it should enable Push profile and decrypt the keys.
* Then it gets started with channel creation on Dev environment

### Current Behaviour

It keeps on reloading when you click on Create channel, Everytime there is a pop up of Enable Push profile signature

https://github.com/push-protocol/push-dapp/assets/12568291/c7327387-8d78-4672-9c0c-5f49b920423c

### Reproduction steps

```bash
1. Go to 'dev.push.org'
2. Click on 'Channel creation'
3. Scroll down to 'channel creation button'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Dapp Env

Dev (dev.push.org)

### Browsers

Chrome

**Comment by rohitmalhotra1420** [comment]
Fixed with the new flow already.
