### ISSUE TITLE
😈 <Update Page Content Layout>

### ISSUE THREAD

**Issue by corlard3y** [push-protocol/push-dapp#1677]
### Describe the Enhancement

At the moment we have three different content layouts
- First: The one we have on chat page where the chat container has fixed height, width and padding across it.
- Second: The one on govern, rewards page and dashboard page where the content is aligned in center for larger screen sizes.
- Third: On Channels page where the container is stacked to right and bottom without any spacing.

We will move all these layouts inside ContentLayout component and use this ContentLayout where ever required. We can introduce a type prop which will decide the layout.

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Dapp Env

Prod (app.push.org), Staging (staging.push.org), Dev (dev.push.org)

**Comment by rohitmalhotra1420** [comment]
Already done in another ticket.
