### ISSUE TITLE
🐛 [BUG] - Chat counter on receiving new chat is bugged

### ISSUE THREAD

**Issue by 0x12zee** [push-protocol/push-dapp#1866]
### Expected Behaviour

When a user receives a new chat, the counter should correctly display number of chats received. 

### Current Behaviour

When a user receives one chat message, the counter shows double. 

### Reproduction steps

```bash
1. Send an address a chat using app.push.org/chat
2. Go to that address and see how many chats does counter shows
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Dapp Env

Prod (app.push.org)

**Comment by abhishek-01k** [comment]
https://www.loom.com/share/590f4141b127407a9140dca436604dcb?sid=a1928ca6-5cb5-4205-8821-fcc50c7949f4

This is fixed now. Recorded a video on dev env
